Repository edgexfoundry/docker-edgex-consul, pull requests merged in 2019-11, with the labels that each got.

#7 consul-svc-healthy: use system jq if available
  scripts/consul-svc-healthy.sh
Labels: fuji

#9 Add health check scripts for the security services (master)
  scripts/security-proxy-setup-checker.sh
  scripts/security-secrets-setup-checker.sh
  scripts/security-secretstore-setup-checker.sh
Labels: geneva

#11 Update docker tag to match branch name
  Jenkinsfile
Labels: fuji, geneva

#10 Update the security-secrets-checker script
  scripts/security-serets-setup-checker.sh
Labels: geneva
